 Reglas, dependencias y acciones. 

hola: hola.cpp //esto es el objetivo y cuando lo llamo hace lo que le pida. El "hola.cpp" quiere decir que solo haga las acciones cuando el arhcivo de salida de hola sea mas viejo que hola.cpp (Esto es para que no lo haga si no tenemos nada guardado).
	g++ hola.cpp -o hola	//Esto es una acción.
